version: '3'

services:
  server:
    build: .
    volumes: 
      - "./:/app"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - HOST=localhost:8000
